server:
  port: 9093
  shutdown-hook: true

cors:
  enabled: true
  allow-origins: [ "*" ]
  allow-methods: [ "*" ]
  allow-headers: [ "*" ]
  allow-credentials: false
  max-age: 7200

db:
  application-name: "mahu"
  url: "${MAHU_DB_URL}"
  username: "${MAHU_DB_USERNAME}"
  password: "${MAHU_DB_PASSWORD}"
  min-idle: 1
  max-size: 64
