parameters:
  - name: attribute_id
    in: path
    description: 属性 ID
    schema:
      type: integer
      format: int32
  - name: attribute_value_id
    in: path
    description: 属性值 ID
    schema:
      type: integer
      format: int32
put:
  summary: 修改商品属性值
  operationId: updateMarketAttributeValue
  x-role-permit: MARKET_ATTRIBUTE:U
  tags:
    - market
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/UpsertMarketAttributeValueRequest.yaml
  responses:
    204:
      description: OK
delete:
  summary: 删除商品属性值
  operationId: deleteMarketAttributeValue
  x-role-permit: MARKET_ATTRIBUTE:D
  tags:
    - market
  responses:
    204:
      description: OK
get:
  summary: 获取商品属性值
  operationId: getMarketAttributeValue
  x-role-permit: MARKET_ATTRIBUTE:R
  tags:
    - market
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/GetMarketAttributeValueResponse.yaml
