parameters:
  - name: attribute_id
    in: path
    description: 属性 ID
    schema:
      type: integer
      format: int32
post:
  summary: 新建商品属性值
  operationId: createMartAttributeValue
  x-role-permit: MART_ATTRIBUTE:W
  tags:
    - mart
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/schemas/UpsertMartAttributeValueRequest.yaml"
  responses:
    "204":
      description: OK
