post:
  summary: OSS 直接上传策略
  operationId: makeOssDirectUpload
  tags:
    - base
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - kind
            - file_name
          properties:
            kind:
              type: string
              description: 存储类型
              enum:
                - BRAND
                - MART_ASSET
              x-enum-descriptions:
                - 品牌LOGO
                - 商城资源
            prefix_limit:
              type: string
              description: 前缀限定
            file_name:
              type: string
              description: 文件名称
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/MakeOssDirectUploadResponse.yaml
