server {
    listen              443 ssl http2;
    listen              [::]:443 ssl http2;
    server_name         mahu.houge.cool;
    root                /var/www/mahu.houge.cool;

    # SSL
    ssl_certificate     /etc/nginx/ssl/mahu.houge.cool.crt;
    ssl_certificate_key /etc/nginx/ssl/mahu.houge.cool.key;

    # security
    include             nginxconfig.io/security.conf;

    # logging
    access_log          /var/log/nginx/mahu.houge.cool.access.log combined buffer=512k flush=1m;
    error_log           /var/log/nginx/mahu.houge.cool.error.log warn;

    # index.html fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # additional config
    include nginxconfig.io/general.conf;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name mahu.houge.cool;
    return      301 https://mahu.houge.cool$request_uri;
}
