#file: noinspection YAMLSchemaValidation
openapi: 3.1.1
info:
  title: Mahu 后台接口文档
  version: 1.0.0
  description: |
    ## x-request-id

    `x-request-id` 是一个 HTTP 头字段，用于唯一标识每个请求。它在分布式系统和微服务架构中非常有用，可以帮助跟踪请求在多个服务之间的流动情况，便于日志记录、调试和问题排查。

    ### 作用

    - **请求跟踪**：`x-request-id` 使得每个请求在系统的各个组件之间传递时都有一个唯一的标识符，可以方便地跟踪请求的整个生命周期。
    - **日志关联**：通过在日志中记录 `x-request-id`，可以将不同服务的日志条目关联起来，帮助快速定位和解决问题。
    - **性能监控**：结合 `x-request-id` 和其他监控工具，可以更准确地测量请求的处理时间和服务间的延迟。
    - **调试和故障排除**：当出现问题时，可以通过 `x-request-id` 快速找到相关的日志和数据，从而更快地进行故障排除。

    ### 生成方法

    `x-request-id` 应该是全局唯一的，并且通常使用 Base58 编码的短 UUID 字符串来实现。以下是一个示例，展示了如何在 Java 中生成一个 Base58 编码的 `x-request-id`：

    ```java
    import java.util.UUID;

    public class RequestIdGenerator {
        public static String generateRequestId() {
            var uuid = UUID.randomUUID();
            var buf = ByteBuffer.allocate(16);
            buf.putLong(uuid.getMostSignificantBits());
            buf.putLong(uuid.getLeastSignificantBits());
            return Base58.encode(buf.array());
        }

        public static void main(String[] args) {
            String requestId = generateRequestId();
            System.out.println("Generated x-request-id: " + requestId);
        }
    }
    ```

    上述代码会生成一个 16 字节的 UUID，并将其转换为 Base58 编码的字符串。

    ### 使用方法

    - **客户端发送请求**：客户端在发送请求时，可以在 HTTP 头中添加 `x-request-id` 字段。如果客户端没有提供 `x-request-id`，服务端可以自动生成一个并返回给客户端。
    - **服务端接收请求**：服务端接收到请求后，会读取 `x-request-id` 并在整个请求处理过程中保持该标识符不变。服务端还可以在响应头中返回 `x-request-id`，以便客户端在后续请求中使用相同的标识符。
    - **日志记录**：在每个服务的日志中记录 `x-request-id`，确保每个日志条目都包含这个标识符，以便于后续的分析和关联。

    ### 示例

    #### 客户端发送请求

    ```http
    GET /api/resource HTTP/1.1
    Host: example.com
    x-request-id: 4Jz2mLrKvRgWjXnY
    ```

    #### 服务端响应

    ```http
    HTTP/1.1 200 OK
    Content-Type: application/json
    x-request-id: 4Jz2mLrKvRgWjXnY

    {
      "data": "some data"
    }
    ```

    ## x-permission-code

    权限代码 (`x-permission-code`) 是用于标识特定权限的字符串。这些权限代码用于系统的权限管理，以确保用户只能访问他们被授权的资源。

    ### 权限代码格式

    权限代码通常由两部分组成：
    1. **权限名称**：表示权限的唯一标识符。
    2. **操作类型**：表示对资源的操作类型，如读取 (R)、写入 (W) 和删除 (D)。

    例如，权限代码 `DICT:R` 表示对字典管理的读取权限。

servers:
  - url: http://127.0.0.1:9093
    description: 本地测试服务
components:
  securitySchemes:
    AT:
      type: http
      in: header
      scheme: Bearer
      description: 访问令牌
security:
  - AT: [ ]
tags:
  - name: h-help
    x-displayName: 帮助接口
  - name: h-login
    x-displayName: 用户登录
  - name: h-me
    x-displayName: 认证用户
  - name: h-file
    x-displayName: 文件系统
  - name: h-public-dict
    x-displayName: 公共字典

  - name: h-auth-client
    x-displayName: 认证终端
  - name: h-dict
    x-displayName: 字典数据
  - name: h-permission
    x-displayName: 权限管理
  - name: h-role
    x-displayName: 角色管理
  - name: h-admin
    x-displayName: 管理员管理
  - name: h-scheduled-task
    x-displayName: 定时任务
  - name: log
    x-displayName: 业务日志
x-tagGroups:
  - name: 基础模块
    tags:
      - h-help
      - h-login
      - h-me
      - h-file
      - h-public-dict
  - name: 系统模块
    tags:
      - h-auth-client
      - h-dict
      - h-permission
      - h-role
      - h-admin
      - h-scheduled-task
paths:
  /samples:
    $ref: "paths/samples.yaml"
  ### =============================== 公共数据接口 =============================== ###
  /info:
    $ref: "paths/info.yaml"
  /p/dicts:
    $ref: "paths/p_dicts.yaml"
  /p/dicts/{dc}:
    $ref: "paths/p_dicts_{dc}.yaml"

  ### =============================== 认证/用户数据接口 =============================== ###
  /login/token:
    $ref: "paths/login_token.yaml"
  /me/profile:
    $ref: "paths/me_profile.yaml"
  /me/password:
    $ref: "paths/me_password.yaml"

  /files/presigned-upload:
    $ref: "paths/files_presigned-upload.yaml"
  ### =============================== 系统模块接口 =============================== ###
  /sys/auth-clients:
    $ref: "paths/sys_auth-clients.yaml"
  /sys/auth-clients/{client_id}:
    $ref: "paths/sys_auth-clients_{client_id}.yaml"
  /sys/dicts:
    $ref: "paths/sys_dicts.yaml"
  /sys/dicts/{dict_type_id}:
    $ref: "paths/sys_dicts_{dict_type_id}.yaml"
  /sys/permissions:
    $ref: "paths/sys_permissions.yaml"
  /sys/roles:
    $ref: "paths/sys_roles.yaml"
  /sys/roles/{role_id}:
    $ref: "paths/sys_roles_{role_id}.yaml"
  /sys/admins:
    $ref: "paths/sys_admins.yaml"
  /sys/admins/{admin_id}:
    $ref: "paths/sys_admins_{admin_id}.yaml"
  /sys/scheduled-tasks:
    $ref: "paths/sys_scheduled-tasks.yaml"
  /sys/scheduled-tasks/{task_name}/exes:
    $ref: "paths/sys_scheduled-tasks_{task_name}_exes.yaml"
  /sys/admin-logs/{type}:
    $ref: "paths/sys_admin-logs_{type}.yaml"
