### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 用户密码登录
POST http://127.0.0.1:9093/login/token
Content-Type: application/json

{
    "grant_type": "password",
    "client_id": "01JCTAWH7NZRHHJZG9DPQ1SFFG",
    "username": "houge",
    "password": "123456"
}
