### 新建角色
POST {{base_uri}}/sys/roles
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "id": {{$random.integer(1, 999999)}},
    "name": "{{$random.name.name}}",
    "remark": "{{$random.lorem.paragraph}}",
    "ordering": {{$random.integer(1, 9999)}},
    "permissions": ["A", "B", "C"]
}


### 角色分页列表
GET {{base_uri}}/sys/roles?size=20
Authorization: Bearer {{access_token}}
