info:
  name: "mahu-admin"
  env: "dev"

server:
  port: 9090
  shutdown-hook: true
  features:
    # 禁止默认启用由程序自定义观测功能
    observe:
      enabled: false

# 跨域配置
cors:
  enabled: true
  allow-origins: ["*"]
  allow-methods: ["*"]
  allow-headers: ["*"]
  allow-credentials: false
  max-age: 7200

db:
  name: "${info.name}"
  url: "jdbc:postgresql://127.0.0.1:5432/mahu"
  username: "postgres"
  password: "postgres"
  min-idle: 1
  max-size: 64
