sources:
  - type: environment-variables
  - type: system-properties

  ### =============== 开发配置 =============== ###
  - type: file
    properties:
      path: /Users/yein/houge/mahu.yaml
      optional: true
  - type: file
    properties:
      path: C:/houge/mahu.yaml
      optional: true
  ### =============== 开发配置 =============== ###

  - type: classpath
    properties:
      resource: application.yaml
  - type: classpath
    properties:
      resource: mahu-admin.yaml
